version: 2
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
        steps:
          - run: yarn install
          - run: yarn build
  deploy:
    steps:
      - checkout
      - run:
          name: Add dokku remote to git
          command: git remote add dokku dokku@172.105.84.80:learn-islam-backend
      - run:
          name: Deploy to remote server
          command: git push dokku master
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          filters:
            branches:
              only: master
