version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: yarn build

  deploy:
    machine: # executor type
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: git remote add dokku dokku@172.105.84.80:learn-islam-backend
      - run: push dokku master

workflows:
    build:
      jobs:
        - build:
            filters:
              branches:
                ignore: master
    deploy:
      jobs:
        - deploy:
            filters:
              branches:
                only: master